spring:
  rabbitmq:
    host: ${RABBITMQ_HOST:127.0.0.1}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:smartoffice}
    password: ${RABBITMQ_PASSWORD:123456}
    virtual-host: ${RABBITMQ_VHOST:/}
