server:
  port: 9105

spring:
  application:
    name: smart-office-attendance-service
  cloud:
    nacos:
      discovery:
        enabled: ${NACOS_DISCOVERY_ENABLED:true}
        register-enabled: ${NACOS_REGISTER_ENABLED:true}
        server-addr: ${NACOS_SERVER_ADDR:127.0.0.1:8848}
    service-registry:
      auto-registration:
        enabled: ${SERVICE_REGISTRY_AUTO_REGISTRATION_ENABLED:true}

management:
  endpoints:
    web:
      exposure:
        include: health,info
