spring:
  cloud:
    nacos:
      server-addr: ${NACOS_SERVER_ADDR:127.0.0.1:8848}
      username: ${NACOS_USERNAME:nacos}
      password: ${NACOS_PASSWORD:nacos}
      discovery:
        server-addr: ${NACOS_SERVER_ADDR:127.0.0.1:8848}
        enabled: ${NACOS_DISCOVERY_ENABLED:true}
        register-enabled: ${NACOS_REGISTER_ENABLED:true}
        group: ${NACOS_DISCOVERY_GROUP:DEFAULT_GROUP}
      config:
        server-addr: ${NACOS_SERVER_ADDR:127.0.0.1:8848}
        username: ${NACOS_USERNAME:nacos}
        password: ${NACOS_PASSWORD:nacos}
        enabled: ${NACOS_CONFIG_ENABLED:true}
        group: ${NACOS_CONFIG_GROUP:DEFAULT_GROUP}
        file-extension: yaml
  config:
    import:
      - optional:nacos:${spring.application.name}.yaml
      - optional:nacos:shared-spring.yaml
      - optional:nacos:shared-redis.yaml
      - optional:nacos:shared-logs.yaml
      - optional:nacos:shared-feign.yaml
